name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Checkout the code from the repository
     
      - name: Set up JDK 17  # Set up Java 17 for Maven build
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Grant execute permission for Maven wrapper
        run: chmod +x ./GateWay/mvnw  # Ensure the Maven wrapper is executable

      - name: Build with Maven
        working-directory: ./GateWay  # Go to the GateWay folder where the Maven project is located
        run: ./mvnw clean package -DskipTests  # Build the JAR with Maven (skip tests for faster build)
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Set up DOCKER_USERNAME in GitHub secrets
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: List files in target directory  # Check if the JAR file is created
        run: ls -al ./GateWay/target  # List the files in the target directory to verify JAR creation

      - name: Build Docker image
        run: |
         docker build -t salmachamam/my-docker-image-name:latest .

      - name: Push Docker image
        run: |
         docker push salmachamam/my-docker-image-name:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
     

     


     
    
