name: userauthentification CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Grant execute permission for Maven wrapper
        run: chmod +x ./userAuthentification/mvnw

      - name: Wait for PostgreSQL to be ready
        run: until pg_isready -h localhost -p 5432 -U postgres; do echo "Waiting for postgres..."; sleep 5; done

      - name: Build with Maven
        working-directory: ./userAuthentification
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/${{ secrets.POSTGRES_DB }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: ./mvnw -B package
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Set up DOCKER_USERNAME in GitHub secrets
          password: ${{ secrets.DOCKER_PASSWORD }}



      - name: List files in target directory  # Check if the JAR file is created
        run: ls -al ./userAuthentification/target  # List the files in the target directory to verify JAR creation

      - name: Build Docker Image for userauthentification
        working-directory: ./userAuthentification  # Go to the GateWay folder
        run: docker build -t salmachamam/userauthentification-image:latest .

        
      - name: Push Docker Image
        run: |
         docker push salmachamam/userauthentification-image:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}



